###

# @name criar_cliente
POST  http://localhost:3333/customers/sign-in
Content-Type: application/json

{
  "email": "cliente-comum1@hotmail.com",
  "password": "123456",
  "cpf": "12345678913",
  "name": "John Doe",
  "phone": "12345678916"
}

###


# @name autenticar_cliente
POST http://localhost:3333/customers/sign-up
Content-Type: application/json

{
  "email": "johndoe@hotmail.com",
  "password": "123456"
}

###


# @name criar_servico(admin-only)
# para testar, gerar token na rota de autenticação com a conta de administrador e colocar o token no cookie
POST http://localhost:3333/services/new-service
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJxdDd4d2ZhMzZxOXpoc3o3NTJkZnlkZnoiLCJpYXQiOjE3NDIxNzcyMzYsImV4cCI6MTc0MjE4MDgzNn0.HoSiJ_WdbYpgUDJaXZRDNOGulIbd9bZhhWt_OZRui8M

{
  "name": "Service 1",
  "description": "Service 1 description",
  "priceInCents": 100,
  "durationInMinutes": 60
}

###

# @name criar_agendamento
POST http://localhost:3333/orders/create-order
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJxdDd4d2ZhMzZxOXpoc3o3NTJkZnlkZnoiLCJpYXQiOjE3NDIyMjA3MjYsImV4cCI6MTc0MjIyNDMyNn0.YpkA2kykNsvXA6QuLAYvGMxHii2xWQ5QCGC0JjFda4o

{
  "orderDate": "2025-03-17T12:00:00",
  "servicesId": [1,2]
}

###

# @name update_agendamento
PATCH  http://localhost:3333/orders/update-order/2
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJxdDd4d2ZhMzZxOXpoc3o3NTJkZnlkZnoiLCJpYXQiOjE3NDIyMTM1MzAsImV4cCI6MTc0MjIxNzEzMH0.yJkNyoFoWRJvGXieC2uirsNEhuQz3BMV7xME6E9kktk

{
  "orderDate": "2025-03-17T16:45:33",
  "servicesId": [1]
}

###

# @name estatisticas_semanais(admin-only)

GET http://localhost:3333/orders/weekly-stats?date=2025-03-17
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJxdDd4d2ZhMzZxOXpoc3o3NTJkZnlkZnoiLCJpYXQiOjE3NDIyMTIyNjAsImV4cCI6MTc0MjIxNTg2MH0.But4DTZJRXZSn9bt59rdRMpe7kxLRfjKnV0KpcDxhJw


###

# @name pedidos-pendentes-da-semana-da-data(admin-only)
GET http://localhost:3333/orders/pending-orders?date=2025-03-17
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJxdDd4d2ZhMzZxOXpoc3o3NTJkZnlkZnoiLCJpYXQiOjE3NDIyMjA3MjYsImV4cCI6MTc0MjIyNDMyNn0.YpkA2kykNsvXA6QuLAYvGMxHii2xWQ5QCGC0JjFda4o